name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # In this step, this action saves a list of existing images,
    # the cache is created without them in the post run.
    # It also restores the cache if it exists.
    - uses: satackey/action-docker-layer-caching@v0.0.5

    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag test:latest

    #- name: running docker
    #  run: docker run test:latest pytest -vs


    - name: build short
      run: docker build . --file Dockerfile_short -t test_short:latest

  run_job:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: satackey/action-docker-layer-caching@v0.0.5
    - name: run short
      run: docker run test_short python /code/code.py

  run_job_2:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: satackey/action-docker-layer-caching@v0.0.5
    - name: run short
      run: docker run test_short python /code/code.py
