name: dock_test
on: [push]

jobs:
  cont:
    runs-on: ubuntu-latest
    name: A job to say hello
    container: continuumio/miniconda
    steps:
    - name: pwd in cont
      run: pwd
    - name: What OS is running
      run: uname -a
    - name: python
      run: python --version
    - name: bash python
      run: bash -c "python --version"


#    - uses: actions/checkout@v2
#    - name: Hello world action step
#      id: hello
#      uses: ./.github/actions
#      with:
#        who-to-greet: 'Mona the Octocat'
    # Use the output from the `hello` step
#    - name: Get the output time
#      run: echo "The time was ${{ steps.hello.outputs.time }}"